# Generated by Django 5.1.6 on 2025-02-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PSNEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolved_or_not",
                    models.CharField(
                        choices=[("R", "Resolved"), ("NR", "Not Resolved")],
                        default="NR",
                        max_length=12,
                    ),
                ),
            ],
        ),
    ]
