# Generated by Django 5.1.6 on 2025-02-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="psnentry",
            name="engineer_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="issue",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="psn",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="resolved_or_not",
            field=models.BooleanField(default=False),
        ),
    ]
