# Generated by Django 5.1.6 on 2025-02-25 10:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0002_psnentry_engineer_name_psnentry_issue_psnentry_psn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psnentry",
            name="date_of_complaint",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="psnentry",
            name="date_of_delivery_to_customer",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="device_activity_completion",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="fitted_at_customer_vehicle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="location_to_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="repair_priority_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="repaired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="request_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="shipped_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
