# Generated by Django 5.1.6 on 2025-02-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0003_psnentry_date_of_complaint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psnentry",
            name="date_of_delivery_to_customer",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="device_activity_completion",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="location_to_delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="repair_priority_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="shipped_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
