# Generated by Django 5.1.6 on 2025-02-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0004_alter_psnentry_date_of_delivery_to_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psnentry",
            name="manager_approval_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
