# Generated by Django 5.1.6 on 2025-02-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0006_remove_psnentry_date_of_complaint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psnentry",
            name="engineer_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="issue",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="manager_approval_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="psn",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="resolved_or_not",
            field=models.BooleanField(default=False),
        ),
    ]
