# Generated by Django 5.1.6 on 2025-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0007_alter_psnentry_engineer_name_alter_psnentry_issue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psnentry",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
