# Generated by Django 5.1.6 on 2025-02-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0009_psnentry_unique_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psnentry",
            name="unique_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
