# Generated by Django 5.1.6 on 2025-02-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0010_alter_psnentry_unique_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psnentry",
            name="resolved_or_not",
        ),
        migrations.AddField(
            model_name="psnentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("Returnable", "Returnable"),
                    ("Non-Returnable", "Non-Returnable"),
                ],
                default="Returnable",
                max_length=20,
            ),
        ),
    ]
