# Generated by Django 5.1.6 on 2025-02-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0011_remove_psnentry_resolved_or_not_psnentry_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="psnentry",
            name="date_of_complaint",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="date_of_delivery_to_customer",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="device_activity_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="engineer_email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="fitted_at_customer_vehicle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="location_to_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="repair_priority_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="repaired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="shipped_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
