# Generated by Django 5.1.6 on 2025-02-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0012_psnentry_date_of_complaint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psnentry",
            name="grn_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="reused_for_field",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("Returnable", "Returnable"),
                    ("Non-Returnable", "Non-Returnable"),
                ],
                default="Returnable",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="issue",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="manager_approval_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="psn",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="unique_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
