# Generated by Django 5.1.6 on 2025-03-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0013_psnentry_grn_no_psnentry_reused_for_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psnentry",
            name="hod_approval_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("Returnable", "Returnable"),
                    ("Non-Returnable", "Non-Returnable"),
                ],
                default="Returnable",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="device_activity_completion",
            field=models.CharField(default="--", max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="engineer_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="engineer_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="fitted_at_customer_vehicle",
            field=models.CharField(default="--", max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="grn_no",
            field=models.CharField(default="--", max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="issue",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="location_to_delivery_date",
            field=models.CharField(default="--", max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="manager_approval_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="psn",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="repaired",
            field=models.CharField(default="--", max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="reused_for_field",
            field=models.CharField(default="--", max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="shipped_date",
            field=models.CharField(default="--", max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="unique_number",
            field=models.IntegerField(unique=True),
        ),
    ]
