# Generated by Django 5.1.6 on 2025-03-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0014_psnentry_hod_approval_status_alter_psnentry_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psnentry",
            name="unique_number",
            field=models.IntegerField(default=10000, unique=True),
        ),
    ]
