# Generated by Django 5.1.6 on 2025-03-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "psnapp",
            "0020_rename_date_of_delivery_to_customer_psnentry_date_of_sale_of_device_and_more",
        ),
    ]

    operations = []
