# Generated by Django 5.1.6 on 2025-03-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0023_auto_20250304_0011"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psnentry",
            name="unique_id",
        ),
        migrations.AddField(
            model_name="psnentry",
            name="resolved_or_not",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="engineer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="issue",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="psn",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
