# Generated by Django 5.1.6 on 2025-03-04 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0024_remove_psnentry_unique_id_psnentry_resolved_or_not_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psnentry",
            name="engineer_name",
        ),
        migrations.RemoveField(
            model_name="psnentry",
            name="issue",
        ),
        migrations.AddField(
            model_name="psnentry",
            name="request_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
