# Generated by Django 5.1.6 on 2025-03-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0025_remove_psnentry_engineer_name_remove_psnentry_issue_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psnentry",
            name="request_id",
        ),
        migrations.AddField(
            model_name="psnentry",
            name="engineer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="issue",
            field=models.TextField(blank=True, null=True),
        ),
    ]
