# Generated by Django 5.1.6 on 2025-03-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0026_remove_psnentry_request_id_psnentry_engineer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psnentry",
            name="manager_approval_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
