# Generated by Django 5.1.6 on 2025-03-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0027_psnentry_manager_approval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="psnentry",
            name="engineer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
