# Generated by Django 5.1.6 on 2025-03-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0028_psnentry_engineer_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psnentry",
            name="device_sent_to",
        ),
        migrations.RemoveField(
            model_name="psnentry",
            name="engineer_name",
        ),
        migrations.RemoveField(
            model_name="psnentry",
            name="issue",
        ),
        migrations.RemoveField(
            model_name="psnentry",
            name="manager_approval_status",
        ),
        migrations.RemoveField(
            model_name="psnentry",
            name="psn",
        ),
        migrations.RemoveField(
            model_name="psnentry",
            name="vehicle_usage",
        ),
        migrations.AddField(
            model_name="psnentry",
            name="call_status",
            field=models.CharField(
                choices=[("Closed", "Closed"), ("Pending", "Pending")],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="date_of_closure",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="device_to_be_sent",
            field=models.CharField(
                choices=[
                    ("Goa", "Goa"),
                    ("Hyderabad", "Hyderabad"),
                    ("Chennai", "Chennai"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="final_action_taken",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="final_call_status",
            field=models.CharField(
                choices=[("Closed", "Closed"), ("Pending", "Pending")],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="hod_approval_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="manager_email",
            field=models.EmailField(
                blank=True, default="user_name@example.com", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="vehicle_run",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="active_profile",
            field=models.CharField(
                choices=[
                    ("Airtel", "Airtel"),
                    ("BSNL", "BSNL"),
                    ("Dual", "Dual"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="complaint_raised_by",
            field=models.CharField(
                choices=[
                    ("Dealer", "Dealer"),
                    ("Customer", "Customer"),
                    ("AL Field", "AL Field"),
                    ("AL Service", "AL Service"),
                    ("I-Alert", "I-Alert"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="complaint_raised_through",
            field=models.CharField(
                choices=[
                    ("I-Alert", "I-Alert"),
                    ("Mail", "Mail"),
                    ("Telephone", "Telephone"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="configuration",
            field=models.CharField(
                choices=[
                    ("Operational Mode", "Operational Mode"),
                    ("Plant Mode", "Plant Mode"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="date_of_complaint",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="device_model",
            field=models.CharField(
                choices=[("DL545", "DL545"), ("DL548", "DL548"), ("others", "Others")],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="engineer_recommendation",
            field=models.CharField(
                choices=[
                    ("Repair", "Repair"),
                    ("Replace", "Replace"),
                    ("Monitor", "Monitor"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="external_modification",
            field=models.CharField(
                choices=[
                    ("Air horn", "Air horn"),
                    ("Cabin", "Cabin"),
                    ("Alt-Device", "Alt-Device"),
                    ("Dashboard Modification", "Dashboard Modification"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="issue_analysis",
            field=models.CharField(
                choices=[
                    ("Disk Image", "Disk Image"),
                    ("Sim-Reg issue", "Sim-Reg issue"),
                    ("Sim Expired", "Sim Expired"),
                    ("Battery Reset", "Battery Reset"),
                    ("VIC Issue", "VIC Issue"),
                    ("CAN Issue", "CAN Issue"),
                    ("SW-Issue", "SW-Issue"),
                    ("GPS status", "GPS status"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="issue_identified",
            field=models.CharField(
                choices=[
                    ("Not Powering ON", "Not Powering ON"),
                    ("NRD", "NRD"),
                    ("NO-DATA", "NO-DATA"),
                    ("100%V Packet", "100%V Packet"),
                    ("Partial V Packet", "Partial V Packet"),
                    ("Latency", "Latency"),
                    ("Data loss", "Data loss"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="issue_raised_by_customer",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="resolved_or_not",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="service_engineer_name",
            field=models.CharField(
                choices=[
                    ("Anil", "Anil"),
                    ("Siva", "Siva"),
                    ("Swamy", "Swamy"),
                    ("Rishwanth", "Rishwanth"),
                    ("Gayadhar", "Gayadhar"),
                    ("Arun Maity", "Arun Maity"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="telco_status",
            field=models.CharField(
                choices=[
                    ("Bootstrap", "Bootstrap"),
                    ("Commercial", "Commercial"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="vehicle_support_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("Tipper", "Tipper"),
                    ("E-com", "E-com"),
                    ("Boss", "Boss"),
                    ("Haulage", "Haulage"),
                    ("Passenger", "Passenger"),
                    ("LCV", "LCV"),
                    ("EV-LCV", "EV-LCV"),
                    ("EV M&HV", "EV M&HV"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
    ]
