# Generated by Django 5.1.6 on 2025-03-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0030_psnentry_manager_approval_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psnentry",
            name="resolved_or_not",
            field=models.BooleanField(blank=True, default="Pending", null=True),
        ),
    ]
