# Generated by Django 5.1.6 on 2025-03-11 10:51

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0031_alter_psnentry_resolved_or_not"),
    ]

    operations = [
        migrations.AddField(
            model_name="psnentry",
            name="unique_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="active_profile",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Airtel", "Airtel"),
                    ("BSNL", "BSNL"),
                    ("Dual", "Dual"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="complaint_raised_by",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Dealer", "Dealer"),
                    ("Customer", "Customer"),
                    ("AL Field", "AL Field"),
                    ("AL Service", "AL Service"),
                    ("I-Alert", "I-Alert"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="complaint_raised_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="complaint_raised_through",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("I-Alert", "I-Alert"),
                    ("Mail", "Mail"),
                    ("Telephone", "Telephone"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="configuration",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Operational Mode", "Operational Mode"),
                    ("Plant Mode", "Plant Mode"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="device_iccid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="device_imei",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="device_model",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("DL545", "DL545"),
                    ("DL548", "DL548"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="device_to_be_sent",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Goa", "Goa"),
                    ("Hyderabad", "Hyderabad"),
                    ("Chennai", "Chennai"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="engineer_recommendation",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Repair", "Repair"),
                    ("Replace", "Replace"),
                    ("Monitor", "Monitor"),
                    ("Others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="external_modification",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("--", "--"),
                    ("Air Horn", "Air Horn"),
                    ("Air Cabin", "Air Cabin"),
                    ("Alt-Device", "Alt-Device"),
                    ("Device Modification", "Device Modification"),
                    ("Others", "Others"),
                ],
                max_length=59,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="issue_analysis",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Disk Image", "Disk Image"),
                    ("Sim-Reg issue", "Sim-Reg issue"),
                    ("Sim Expired", "Sim Expired"),
                    ("Battery Reset", "Battery Reset"),
                    ("VIC Issue", "VIC Issue"),
                    ("CAN Issue", "CAN Issue"),
                    ("SW-Issue", "SW-Issue"),
                    ("GPS status", "GPS status"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="issue_identified",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Not Powering ON", "Not Powering ON"),
                    ("NRD", "NRD"),
                    ("NO-DATA", "NO-DATA"),
                    ("100%V Packet", "100%V Packet"),
                    ("Partial V Packet", "Partial V Packet"),
                    ("Latency", "Latency"),
                    ("Data loss", "Data loss"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="manager_email",
            field=models.EmailField(
                blank=True,
                choices=[
                    ("kunal@danlawtech.com", "kunal@danlawtech.com"),
                    ("narendrareddyg@danlawtech.com", "narendrareddyg@danlawtech.com"),
                    ("upendram@danlawtech.com", "upendram@danlawtech.com"),
                ],
                default="user_name@example.com",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="resolved_or_not",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Select one",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="service_engineer_name",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Anil", "Anil"),
                    ("Siva", "Siva"),
                    ("Swamy", "Swamy"),
                    ("Rishwanth", "Rishwanth"),
                    ("Gayadhar", "Gayadhar"),
                    ("Arun Maity", "Arun Maity"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="telco_status",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Bootstrap", "Bootstrap"),
                    ("Commercial", "Commercial"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="vehicle_running_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Tipper", "Tipper"),
                    ("E-com", "E-com"),
                    ("Boss", "Boss"),
                    ("Haulage", "Haulage"),
                    ("Passenger", "Passenger"),
                    ("LCV", "LCV"),
                    ("EV-LCV", "EV-LCV"),
                    ("EV M&HV", "EV M&HV"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
    ]
