# Generated by Django 5.1.6 on 2025-03-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0032_psnentry_unique_id_alter_psnentry_active_profile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="psnentry",
            old_name="vin_number",
            new_name="VIN_number",
        ),
        migrations.RenameField(
            model_name="psnentry",
            old_name="device_psn",
            new_name="device_PSN",
        ),
        migrations.RenameField(
            model_name="psnentry",
            old_name="first_communication_on_darby",
            new_name="first_communication_in_darby",
        ),
        migrations.RenameField(
            model_name="psnentry",
            old_name="issue_raised_by_customer",
            new_name="last_communication_in_darby",
        ),
        migrations.RemoveField(
            model_name="psnentry",
            name="device_iccid",
        ),
        migrations.RemoveField(
            model_name="psnentry",
            name="device_imei",
        ),
        migrations.RemoveField(
            model_name="psnentry",
            name="last_communication_on_darby",
        ),
        migrations.AddField(
            model_name="psnentry",
            name="customer_raised_issue",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="call_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Monitoring", "Monitoring"),
                    ("Closed", "Closed"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="final_call_status",
            field=models.CharField(
                choices=[("--", "--"), ("Closed", "Closed"), ("Pending", "Pending")],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="kilometers_hours",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Kilometers/Hours"
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="vehicle_run",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Kilometers", "Kilometers"),
                    ("Hours", "Hours"),
                    ("Others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="psnentry",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Tipper", "Tipper"),
                    ("E-com", "E-com"),
                    ("Boss", "Boss"),
                    ("Haulage", "Haulage"),
                    ("Passenger", "Passenger"),
                    ("LCV", "LCV"),
                    ("EV-LCV", "EV-LCV"),
                    ("EV M&HV", "EV M&HV"),
                    ("T&T", "T&T"),
                    ("others", "Others"),
                ],
                default="Select one",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="device_ICCID",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="device_IMEI",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
