# Generated by Django 5.1.6 on 2025-03-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0033_rename_vin_number_psnentry_vin_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psnentry",
            name="device_ICCID",
        ),
        migrations.RemoveField(
            model_name="psnentry",
            name="device_IMEI",
        ),
    ]
