# Generated by Django 5.1.6 on 2025-03-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psnapp", "0034_remove_psnentry_device_iccid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psnentry",
            name="device_ICCID",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="psnentry",
            name="device_IMEI",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
